name: Build docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v.*'
    branches:
      - main

env:
  IMAGE_NAME: ci-cd

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compute TAG
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG="${{ github.ref_name }}"
          else
            SHORT_SHA=${GITHUB_SHA:0:7}
            TAG="${{ github.ref_name }}-${SHORT_SHA}-$(date +%s)"
          fi
          echo "Computed TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
